services:
  backend:
    # image: dilipkumar2/contrihub-be:latest
    build: .
    container_name: contrihub-be
    ports:
      - "5050:5050"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=openscout
      - DB_PORT=5432
      # - FRONTEND_URL=https://contri-hub.vercel.app/
      - REDIS_URL=redis:6379
    depends_on:
      - db
      - redis
    restart: unless-stopped
  
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openscout
    # ports:
    #   - "5432:5432"
    volumes:
      - openscout_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    # ports:
    #   - "6379:6379"
    restart: unless-stopped

volumes:
  openscout_pgdata:
